# Generated by Django 3.2.6 on 2022-06-20 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255)),
                ('json_kwargs', models.TextField(blank=True)),
                ('json_result', models.TextField(blank=True)),
                ('input_file', models.CharField(blank=True, max_length=255)),
                ('input_filename', models.CharField(blank=True, max_length=255)),
                ('output_file', models.CharField(blank=True, max_length=255)),
                ('output_filename', models.CharField(blank=True, db_index=True, max_length=255)),
                ('log_history_file_size', models.IntegerField(default=0)),
                ('count_row_complete', models.IntegerField(default=0)),
                ('count_row', models.IntegerField(default=0)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('datetime_start', models.DateTimeField(default=None, null=True)),
                ('datetime_end', models.DateTimeField(default=None, null=True)),
                ('is_force', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(-6, 'Is Force'), (-5, 'Timeout'), (-4, 'Error'), (-3, 'File Error'), (-2, 'Result Delete'), (-1, 'Fail'), (0, 'Upload'), (1, 'Wait'), (2, 'Process'), (3, 'Success'), (4, 'Downloading')])),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('action_type', models.IntegerField(choices=[(0, 'other'), (1, 'export'), (2, 'import'), (3, 'update')], default=0)),
                ('module_name', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_create'],
                'default_permissions': (),
            },
        ),
    ]
