# Generated by Django 3.2.6 on 2022-04-20 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification_template', '0001_initial'),
        ('inbox', '0002_inbox_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification_template.trigger'),
        ),
    ]
