# Generated by Django 3.2.6 on 2022-02-14 08:54

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='count_age',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='account',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not set'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='id_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=account.models.generate_token_field, editable=False, max_length=120, unique=True)),
                ('status', models.IntegerField(choices=[(-1, 'deactivate'), (1, 'activate'), (2, 'completed'), (3, 'expired')], db_index=True, default=1)),
                ('method', models.IntegerField(choices=[(0, 'not_set'), (1, 'email'), (2, 'phone_number')], db_index=True, default=0)),
                ('send_method', models.IntegerField(choices=[(1, 'email'), (2, 'sms')], db_index=True, default=1)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_expire', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
