# Generated by Django 3.2.6 on 2022-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220214_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='apple_user_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook_user_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_user_id',
        ),
        migrations.AddField(
            model_name='account',
            name='is_get_news',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_share_data',
            field=models.BooleanField(default=True),
        ),
    ]
