# Generated by Django 3.2.6 on 2022-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220228_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kyc_status',
            field=models.IntegerField(choices=[(-1, 'no_process'), (1, 'not_verify'), (2, 'in_review'), (3, 'approve')], default=-1),
        ),
    ]
