# Generated by Django 3.2.6 on 2022-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not set'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0),
        ),
    ]
