# Generated by Django 3.2.6 on 2022-03-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name_thai',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name_thai',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='middle_name_thai',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.IntegerField(choices=[(0, 'Not set'), (1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.')], default=0),
        ),
    ]
