# Generated by Django 3.2.6 on 2022-03-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220303_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='account/KYC/%Y/%m/'),
        ),
    ]
