# Generated by Django 3.2.6 on 2022-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_id_selfie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_operator',
            field=models.BooleanField(default=False),
        ),
    ]
