# Generated by Django 3.2.6 on 2022-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_is_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kyc_status',
            field=models.IntegerField(choices=[(-2, 'reject'), (-1, 'no_process'), (1, 'not_verify'), (2, 'in_review'), (3, 'approve')], default=-1),
        ),
    ]
