# Generated by Django 3.2.6 on 2022-07-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='carbon_saving',
            field=models.IntegerField(default=0),
        ),
    ]
