# Generated by Django 3.2.6 on 2022-07-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_carbon_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='carbon_saving',
            field=models.FloatField(default=0.0),
        ),
    ]
