# Generated by Django 3.2.6 on 2022-08-01 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_requestdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(0, 'Not set'), (1, 'Mr.'), (2, 'Mrs.'), (3, 'Ms.')], default=0)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('first_name_thai', models.CharField(blank=True, db_index=True, max_length=120)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('middle_name_thai', models.CharField(blank=True, db_index=True, max_length=120)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('last_name_thai', models.CharField(blank=True, db_index=True, max_length=120)),
                ('id_card', models.CharField(blank=True, max_length=255, null=True)),
                ('laser_code', models.CharField(blank=True, max_length=255, null=True)),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='account/KYC/%Y/%m/')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='account/KYC/%Y/%m/')),
                ('id_selfie_image', models.ImageField(blank=True, null=True, upload_to='account/KYC/%Y/%m/')),
                ('is_accepted_kyc_consent', models.BooleanField(default=False)),
                ('kyc_status', models.IntegerField(choices=[(-2, 'reject'), (-1, 'no_process'), (1, 'not_verify'), (2, 'in_review'), (3, 'approve')], default=-1)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
