# Generated by Django 3.2.6 on 2022-08-04 14:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_kycaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='ref_code',
            field=models.CharField(db_index=True, default=account.models.generate_ref_code_field, editable=False, max_length=120, unique=True),
        ),
    ]
