# Generated by Django 3.2.6 on 2022-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_identityverification_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycaccount',
            name='is_mobile_verify',
            field=models.BooleanField(default=False),
        ),
    ]
