# Generated by Django 3.2.6 on 2023-03-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20220901_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nft_access_token', 'NFC Access Token')], max_length=255)),
                ('token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('datetime_expire', models.DateTimeField(blank=True, null=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
