# Generated by Django 3.2.6 on 2022-07-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scb_pg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentConfirmation',
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='amount',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='channel_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='currency_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='payee_proxy_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='payer_proxy_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='transaction_datetime',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scbpayment',
            name='transaction_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
