# Generated by Django 3.2.6 on 2022-07-20 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scb_pg', '0002_auto_20220711_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='scbpayment',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scbpayment',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
