# Generated by Django 3.2.6 on 2022-02-14 06:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['date'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Session2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['date'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['date'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['date'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['date'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(-1, '(Not set)'), (0, 'Web'), (1, 'Mobile'), (3, 'Android'), (4, 'iOS'), (10, 'Dashboard')], db_index=True, default=-1)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_create'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ContentViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(db_index=True)),
                ('source', models.IntegerField(choices=[(-1, '(Not set)'), (0, 'Web'), (1, 'Mobile'), (3, 'Android'), (4, 'iOS'), (10, 'Dashboard')], db_index=True, default=-1)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-datetime_create'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-datetime_update'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SessionLog2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('session_key', models.CharField(db_index=True, max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('source', models.IntegerField(choices=[(-1, '(Not set)'), (0, 'Web'), (1, 'Mobile'), (3, 'Android'), (4, 'iOS'), (10, 'Dashboard')], db_index=True, default=-1)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_create'],
                'default_permissions': (),
                'index_together': {('date', 'session_key')},
            },
        ),
    ]
