# Generated by Django 3.2.6 on 2022-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
