# Generated by Django 3.2.6 on 2022-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.IntegerField(choices=[(-1, 'waiting'), (1, 'sent'), (2, 'receive'), (3, 'top_up'), (4, 'activity'), (5, 'withdraw')], db_index=True, default=-1),
        ),
    ]
