# Generated by Django 3.2.6 on 2022-03-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(-3, 'cancel'), (-2, 'reject'), (-1, 'pending'), (1, 'waiting_for_payment'), (2, 'success')], db_index=True, default=-1),
        ),
    ]
