# Generated by Django 3.2.6 on 2022-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rate_per_usdt',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
