# Generated by Django 3.2.6 on 2022-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_rate_per_usdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_by',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
