# Generated by Django 3.2.6 on 2022-03-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='transaction/qrcode/%Y/%m/')),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to='account/payment_slip/%Y/%m/')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('datetime_stamp', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
            options={
                'ordering': ['-datetime_create'],
            },
        ),
    ]
