# Generated by Django 3.2.6 on 2022-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
