# Generated by Django 3.2.6 on 2022-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='thb_value',
            field=models.FloatField(default=0.0),
        ),
    ]
