# Generated by Django 3.2.6 on 2022-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_transaction_thb_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='thb_value',
            new_name='thb_values',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='values',
            field=models.FloatField(default=0.0),
        ),
    ]
