# Generated by Django 3.2.6 on 2022-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20220317_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
