# Generated by Django 3.2.6 on 2022-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_transaction_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime_stamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
