# Generated by Django 3.2.6 on 2022-07-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref_code_1',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_code_2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
