# Generated by Django 3.2.6 on 2022-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.IntegerField(choices=[(-1, 'waiting'), (1, 'sent'), (2, 'receive'), (3, 'top_up'), (4, 'activity'), (5, 'withdraw'), (6, 'swap')], db_index=True, default=-1),
        ),
    ]
