# Generated by Django 3.2.6 on 2022-02-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('app', models.CharField(db_index=True, max_length=24)),
                ('code', models.CharField(db_index=True, max_length=48, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('is_web', models.BooleanField(default=False)),
                ('is_dashboard', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'Boolean'), (2, 'String'), (3, 'Integer'), (4, 'Float'), (5, 'Text'), (6, 'Choices'), (7, 'Color'), (8, 'Image'), (9, 'List'), (10, 'JSON'), (11, 'Function')])),
                ('value', models.CharField(blank=True, max_length=255)),
                ('value_text', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='config/image/')),
                ('sort', models.IntegerField(db_index=True, default=0)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('value_text', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.config')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
