# Generated by Django 3.2.6 on 2022-03-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0009_auto_20220317_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(-2, 'cancel'), (-1, 'pending'), (1, 'food_drink'), (2, 'shopping'), (3, 'transportation')], db_index=True, default=-1)),
                ('code', models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True)),
                ('desc', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('carbon_saving', models.FloatField(default=0.0)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
            options={
                'ordering': ['-datetime_create'],
            },
        ),
    ]
