# Generated by Django 3.2.6 on 2022-07-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20220704_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonactivity',
            name='coin',
            field=models.IntegerField(choices=[(-1, 'no_data'), (1, 'CERO'), (2, 'GREEN'), (3, 'THB')], db_index=True, default=-1),
        ),
        migrations.AddField(
            model_name='carbonactivity',
            name='values',
            field=models.FloatField(default=0.0),
        ),
    ]
