# Generated by Django 3.2.6 on 2022-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_carbonactivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonactivity',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
