# Generated by Django 3.2.6 on 2022-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(db_index=True, default=-1)),
                ('gender', models.IntegerField(choices=[(0, 'Not set'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=-1)),
                ('age', models.IntegerField(db_index=True, default=-1)),
                ('status', models.IntegerField(choices=[(-2, 'inactive'), (-1, 'suspect'), (1, 'active'), (2, 'Delete')], default=0)),
            ],
        ),
    ]
