# Generated by Django 3.2.6 on 2022-07-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_log',
            options={'ordering': ['-id']},
        ),
    ]
