# Generated by Django 3.2.6 on 2022-07-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_log', '0002_alter_account_log_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account_log',
            new_name='AccountLog',
        ),
    ]
