# Generated by Django 3.2.6 on 2022-02-14 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_standard', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('available_condition', models.TextField(blank=True, null=True)),
                ('available_correspond', models.TextField(blank=True, null=True)),
                ('available_param', models.TextField()),
                ('available_subject', models.TextField(blank=True, null=True)),
                ('available_body', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.IntegerField(choices=[(0, 'both'), (1, 'mail'), (2, 'notification')], default=0)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('account_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_template.template')),
            ],
            options={
                'ordering': ['id'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='template',
            name='event_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification_template.trigger'),
        ),
    ]
