name: Build and deploy a container to an VM by acr

on:
  push:
    branches: 
       - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: vekawspocregistry.azurecr.io # default: index.docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
          
      - name: Build and Push docker image to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
             "ENV_FILE: ${{ vars.ENV_FILE }}"
          tags: vekawspocregistry.azurecr.io/co2-backend:latest
          file: ./deployment/Dockerfile.dev
          
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: vekawspocregistry.azurecr.io # default: index.docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy execute command ssh to remote server
        env:
           IMAGE_NAME: vekawspocregistry.azurecr.io/poc-ml:latest
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
              docker pull -f ./deployment/Dockerfile.dev -t vekawspocregistry.azurecr.io/co2-backend:latest
              docker run -d vekawspocregistry.azurecr.io/co2-backend:latest
              docker ps -a
